import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { AppProviders } from "@/components/providers/app-providers";
import { ViewportGate } from "@/components/site/viewport-gate";
import { DEVICE_SCRIPT } from "@/lib/device";
import { RESTORE_SCRIPT } from "@/lib/scroll-restoration";
import { env } from "@/lib/env";
import {
  SITE_CATEGORY,
  SITE_DESCRIPTION,
  SITE_LANG,
  SITE_LOCALE,
  SITE_NAME,
} from "@/lib/site";
import "@/styles/globals.css";

/* Inter drives everything, text and numbers both, because that is what every
   type variable in the live Figma file says. See docs/DECISIONS.md 002.

   Loaded as a variable font: one file covers 400, 500 and 700, which is a
   smaller download than three static cuts and matters against the LCP budget in
   doc 04 §5. Self-hosted and preloaded through next/font rather than fetched
   from Google at runtime, so there is no third-party round trip on the critical
   path and no layout shift. `display: swap` keeps text painted while it lands. */
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const TITLE = `${SITE_NAME} · ${SITE_CATEGORY}`;

/**
 * True while phones and tablets are served the small-screen notice instead of
 * the site. Delete this and the notice together; `robots` below reads it.
 */
const VIEWPORT_GATED = true;

/* Icons, the share card and the manifest are all file conventions rather than
   hand-written tags, so Next emits them with the correct sizes and types and
   they cannot drift from the files on disk:

     src/app/icon.svg              rel="icon", vector
     src/app/favicon.ico           16/32/48 for crawlers and older clients
     src/app/apple-icon.png        180, iOS home screen
     src/app/opengraph-image.png   1200x630, also consumed by X as og:image
     src/app/manifest.ts           web app manifest

   All of them are generated by `npm run ds:build` from the vectors in
   public/brand/. Do not hand-edit them. */

export const metadata: Metadata = {
  metadataBase: new URL(env.siteUrl),

  title: {
    default: TITLE,
    /* Every other page appends the masterbrand, which satisfies doc 01 §4's
       "Tradl AI in full on first mention" without repeating it in body copy. */
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,

  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME, url: env.siteUrl }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  category: "finance",
  referrer: "origin-when-cross-origin",

  alternates: { canonical: "/" },

  /* Stops Safari turning figures into tel: links. This site is full of prices,
     percentages and dates, and an auto-linked number in a ledger is both wrong
     and ugly. */
  formatDetection: { telephone: false, date: false, address: false, email: false },

  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    locale: SITE_LOCALE,
    url: "/",
    title: TITLE,
    description: SITE_DESCRIPTION,
  },

  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: SITE_DESCRIPTION,
  },

  /* Two gates, and both have to be open.
 
     The first is the environment: only the real production deployment is
     indexable, because a preview URL competing with the live site in search
     results is a slow problem to diagnose.
 
     The second is the small-screen notice, and it is the one that will be easy
     to forget. Google indexes mobile-first, so while phones and tablets are
     served a one-screen notice instead of the site, the page a crawler renders
     and stores has no content on it. Being absent from an index is recoverable;
     being in one as an empty page is a worse starting position than not being
     there at all. Delete VIEWPORT_GATED in the same commit that deletes the
     notice, and this reverts to indexable on its own. See docs/DECISIONS.md 009. */
  robots:
    env.shouldIndex && !VIEWPORT_GATED
      ? {
          index: true,
          follow: true,
          googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
        }
      : { index: false, follow: false, nocache: true },

  appleWebApp: { title: SITE_NAME, statusBarStyle: "default" },
};

export const viewport: Viewport = {
  /* One value, not a light/dark pair. The design system has a single mode and
     the site runs on it, so there is nothing to switch between. This is the
     page ground from marketing/ground.css; keep the two in step. */
  themeColor: "#07080a",
  colorScheme: "dark",
};

/**
 * Organization and WebSite entity data.
 *
 * Only facts that are actually known are asserted. Deliberately absent, because
 * inventing them is worse than omitting them: `legalName`, `sameAs` (social and
 * profile URLs), postal address, and the SEBI Research Analyst registration
 * number. Doc 05 §5.8 has the RA number and the footer compliance block still
 * open with legal; when they land, they belong here and in the footer together.
 */
const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${env.siteUrl}/#organization`,
      name: SITE_NAME,
      url: env.siteUrl,
      description: SITE_DESCRIPTION,
      logo: {
        "@type": "ImageObject",
        url: `${env.siteUrl}/icons/icon-512.png`,
        width: 512,
        height: 512,
      },
    },
    {
      "@type": "WebSite",
      "@id": `${env.siteUrl}/#website`,
      name: SITE_NAME,
      url: env.siteUrl,
      description: SITE_DESCRIPTION,
      inLanguage: SITE_LANG,
      publisher: { "@id": `${env.siteUrl}/#organization` },
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  /* No data-theme attribute. The design system declares its one mode on :root,
     the site runs on it, and there is nothing to toggle. See docs/DECISIONS.md 004. */
  return (
    /* `suppressHydrationWarning` is here for exactly one attribute, and it is
       the documented escape hatch for it. The blocking script below stamps
       `data-restoring` on this element before React hydrates, so the DOM
       legitimately carries an attribute the server HTML does not, and React
       reports it as a mismatch. The suppression covers this element's own
       attributes and nothing below it, and the only other attributes here are
       a static lang and a font class. */
    <html lang={SITE_LANG} className={inter.variable} suppressHydrationWarning>
      <body>
        {/* First in the body and deliberately blocking. A reload deep in the
            page cannot be restored until the pinned sections have added their
            spacers, which is after hydration, so without this the visitor
            watches the hero for as long as hydration takes and is then thrown
            to where they were. This arms a flag that hides the body for that
            window; the provider clears it the moment the page is back where it
            was. See src/lib/scroll-restoration.ts. */}
        <script dangerouslySetInnerHTML={{ __html: RESTORE_SCRIPT }} />

        {/* Blocking for the same reason: it decides what the first paint shows.
            It only ever adds an attribute, and only on a touchscreen tablet that
            reports itself as a laptop. See src/lib/device.ts. */}
        <script dangerouslySetInnerHTML={{ __html: DEVICE_SCRIPT }} />

        {/* Below 1024px this replaces the page; above it, it is `display: none`
            and contributes nothing at all. See components/site/viewport-gate. */}
        <ViewportGate />

        <AppProviders>{children}</AppProviders>
        <script
          type="application/ld+json"
          /* JSON.stringify output, not user input. `<` is escaped so the string
             can never close the script element early. */
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(structuredData).replace(/</g, "\\u003c"),
          }}
        />
      </body>
    </html>
  );
}
