import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { AppProviders } from "@/components/providers/app-providers";
import { env } from "@/lib/env";
import {
  SITE_CATEGORY,
  SITE_DESCRIPTION,
  SITE_LANG,
  SITE_LOCALE,
  SITE_NAME,
} from "@/lib/site";
import "@/styles/globals.css";

/* Inter drives everything, text and numbers both, because that is what every
   type variable in the live Figma file says. See docs/DECISIONS.md 002.

   Loaded as a variable font: one file covers 400, 500 and 700, which is a
   smaller download than three static cuts and matters against the LCP budget in
   doc 04 §5. Self-hosted and preloaded through next/font rather than fetched
   from Google at runtime, so there is no third-party round trip on the critical
   path and no layout shift. `display: swap` keeps text painted while it lands. */
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const TITLE = `${SITE_NAME} · ${SITE_CATEGORY}`;

/* Icons, the share card and the manifest are all file conventions rather than
   hand-written tags, so Next emits them with the correct sizes and types and
   they cannot drift from the files on disk:

     src/app/icon.svg              rel="icon", vector
     src/app/favicon.ico           16/32/48 for crawlers and older clients
     src/app/apple-icon.png        180, iOS home screen
     src/app/opengraph-image.png   1200x630, also consumed by X as og:image
     src/app/manifest.ts           web app manifest

   All of them are generated by `npm run ds:build` from the vectors in
   public/brand/. Do not hand-edit them. */

export const metadata: Metadata = {
  metadataBase: new URL(env.siteUrl),

  title: {
    default: TITLE,
    /* Every other page appends the masterbrand, which satisfies doc 01 §4's
       "Tradl AI in full on first mention" without repeating it in body copy. */
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,

  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME, url: env.siteUrl }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  category: "finance",
  referrer: "origin-when-cross-origin",

  alternates: { canonical: "/" },

  /* Stops Safari turning figures into tel: links. This site is full of prices,
     percentages and dates, and an auto-linked number in a ledger is both wrong
     and ugly. */
  formatDetection: { telephone: false, date: false, address: false, email: false },

  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    locale: SITE_LOCALE,
    url: "/",
    title: TITLE,
    description: SITE_DESCRIPTION,
  },

  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: SITE_DESCRIPTION,
  },

  /* Only the real production deployment is indexable. A preview URL competing
     with the live site in search results is a slow problem to diagnose. */
  robots: env.shouldIndex
    ? {
        index: true,
        follow: true,
        googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
      }
    : { index: false, follow: false, nocache: true },

  appleWebApp: { title: SITE_NAME, statusBarStyle: "default" },
};

export const viewport: Viewport = {
  /* One value, not a light/dark pair. The design system has a single mode and
     the site runs on it, so there is nothing to switch between. This is the
     page ground from marketing/ground.css; keep the two in step. */
  themeColor: "#121212",
  colorScheme: "dark",
};

/**
 * Organization and WebSite entity data.
 *
 * Only facts that are actually known are asserted. Deliberately absent, because
 * inventing them is worse than omitting them: `legalName`, `sameAs` (social and
 * profile URLs), postal address, and the SEBI Research Analyst registration
 * number. Doc 05 §5.8 has the RA number and the footer compliance block still
 * open with legal; when they land, they belong here and in the footer together.
 */
const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${env.siteUrl}/#organization`,
      name: SITE_NAME,
      url: env.siteUrl,
      description: SITE_DESCRIPTION,
      logo: {
        "@type": "ImageObject",
        url: `${env.siteUrl}/icons/icon-512.png`,
        width: 512,
        height: 512,
      },
    },
    {
      "@type": "WebSite",
      "@id": `${env.siteUrl}/#website`,
      name: SITE_NAME,
      url: env.siteUrl,
      description: SITE_DESCRIPTION,
      inLanguage: SITE_LANG,
      publisher: { "@id": `${env.siteUrl}/#organization` },
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  /* No data-theme attribute. The design system declares its one mode on :root,
     the site runs on it, and there is nothing to toggle. See docs/DECISIONS.md 004. */
  return (
    <html lang={SITE_LANG} className={inter.variable}>
      <body>
        <AppProviders>{children}</AppProviders>
        <script
          type="application/ld+json"
          /* JSON.stringify output, not user input. `<` is escaped so the string
             can never close the script element early. */
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(structuredData).replace(/</g, "\\u003c"),
          }}
        />
      </body>
    </html>
  );
}
